Part1
dnbaumann/PFMCPP_Project2 pull request #1
Opened 2022-02-04 01:30 UTC by dnbaumann

I think this is "done"

2022-02-04 19:38 UTC, matkatmusic requested changes
Your function names do not conform to this mantra:
- Name objects what they are
- name functions what they do.
Example:
 ```
auto lastYearProfit = profit(12.99, 2.99,10.0);
```
`profit` is not an action.  it is a noun.
`computeProfit` is an action.  it has a verb in the name.

It's important to establish this habit of using great names for your functions now before you get further into the course.

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +        ignoreUnused(boy); //
FIXME:
```
b) at the end of the function, call ignoreUnused once and pass all of your variables to it.
```
FIXME:
- initialize `char` types by writing a single alpha-numeric wrapped in Single Quotes.
FIXME:
- all code inside `{ }` should have the same indentation.
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +{
Function declarations need to line up with the left edge of the text editor
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> + }
Curly braces need to line up with the left edge of the start of the function declaration
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +{
Function declarations need to line up with the left edge of the text editor
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +{
Function declarations need to line up with the left edge of the text editor
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +{
Function declarations need to line up with the left edge of the text editor
- [ ] revise

2022-02-04 19:38 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(carRented,teacherEval,lastYearProfit,nextMonthRent,actualSpeed, formattedMessage,dontCarry,winner, canBeDragged,readyToDeliver,willBeReady);
Add 1 space after `,` to make the the code more readable
- [ ] revise

2022-02-04 19:42 UTC, dnbaumann commented on main.cpp
> +        ignoreUnused(boy); //
Great comments.  will fix right away.  I went back and forth on whether to write just one line or many.  If you're bored, I can show why I felt the balance of your instructions led to the way I did it as I already coded it the way you requested and changed it back (i.e., one or many ignoreUnused in the first part).

2022-02-05 18:41 UTC, dnbaumann commented on main.cpp
> +    ignoreUnused(carRented,teacherEval,lastYearProfit,nextMonthRent,actualSpeed, formattedMessage,dontCarry,winner, canBeDragged,readyToDeliver,willBeReady);
Did my best to resolve all errors and address all comments.  I'll admit I'm really struggling.  Not with the concepts, but I have to learn to adapt to my handicap.  My left-hand shakes badly and I have wiped out hours of work in more ways than I can count.  Just one twitch while a large block of text is highlighted and it's gone if you don't notice.  I'll get better, and i need to get used to these random twitches.  I'm going to start saving copies to an external editor so it's harder for me to clobber work.  In all events, I'm sure I still have something wrong in here.  Your assistance will be appreciated.

2022-02-06 03:03 UTC, dnbaumann commented on main.cpp
> +    ignoreUnused(carRented,teacherEval,lastYearProfit,nextMonthRent,actualSpeed, formattedMessage,dontCarry,winner, canBeDragged,readyToDeliver,willBeReady);
I believe everything is resolved and it compiles.  Your comments are welcome as always.

2022-02-06 03:28 UTC, matkatmusic approved these changes

2022-02-06 03:28 UTC, merged